# Generated by Django 6.0.5 on 2026-05-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
