# Generated by Django 6.0.5 on 2026-05-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_rename_parent_id_department_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="organization.department",
                verbose_name="Родительское подразделение",
            ),
        ),
    ]
