# Generated by Django 6.0.5 on 2026-05-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_department_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="organization.department",
                verbose_name="Подразделение",
            ),
        ),
    ]
